title: Najib Adan # your name (or website title) here
logo: "/images/logo.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  I am Data Analyst with one year experience.
  <br><br>
  I currently work at a government owned state company in the oil and gas industry where I design and implement solutions for departments. 
  Recently I have been researching about using drones with computer vision in detecting objects and actions. 
  <br><br>
  <a href="https://www.linkedin.com/in/najib-adan-639612181/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
